dist: bionic
language: cpp
addons:
  apt:
    update: true
    packages:
      - qt5-default
      - googletest

install:
  - pushd /usr/src/googletest
  - sudo mkdir build
  - sudo chown -R $(whoami) build
  - cd build
  - cmake ..
  - cmake --build .
  - find -name "*.a" -exec sudo cp {} /usr/local/lib/ \;
  - cd ..
  - sudo rm -rf build
  - popd

compiler:
  - gcc
  - clang

script: mkdir build && cd build && cmake -DQPAGEDPROXYMODEL_BUILD_TESTS=ON -DCMAKE_CXX_COMPILER="$CXX" -DCMAKE_C_COMPILER="$C" .. && cmake --build . && ctest
