dist: xenial
language: cpp
addons:
  apt:
    update: true
    packages:
      - qt5-default

install:
  - pushd /tmp
  - wget https://github.com/google/googletest/archive/release-1.8.1.tar.gz
  - tar -zxvf release-1.8.1.tar.gz
  - cd googletest-release-1.8.1
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - sudo $(which cmake) --build . --target install
  - popd

compiler:
  - gcc
  - clang

script: mkdir build && cd build && cmake -DQPAGEDPROXYMODEL_BUILD_TESTS=ON -DCMAKE_CXX_COMPILER="$CXX" -DCMAKE_C_COMPILER="$C" .. && cmake --build . && ctest
