dist: bionic
language: cpp
addons:
  apt:
    update: true
    packages:
      - googletest
      - gcovr

install:
  - pushd /usr/src/googletest
  - sudo mkdir build
  - sudo chown -R $(whoami) build
  - cd build
  - cmake ..
  - cmake --build .
  - find -name "*.a" -exec sudo cp {} /usr/local/lib/ \;
  - cd ..
  - sudo rm -rf build
  - popd
  - if [ "$QT_VERSION" = "4" ]; then sudo apt install -qqy qt4-default; fi
  - if [ "$QT_VERSION" = "5" ]; then sudo apt install -qqy qt5-default; fi

env:
  - QT_VERSION="4"
  - QT_VERSION="5"

compiler:
  - gcc
  - clang

script: 
  - mkdir build 
  - cd build
  - cmake -DQPAGEDPROXYMODEL_BUILD_TESTS=ON -DQPAGEDPROXYMODEL_COVERAGE=ON -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER="$CXX" -DCMAKE_C_COMPILER="$C" .. 
  - cmake --build . 
  - ctest

after_success:
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
